### ISSUE TITLE
Where do I put require: .. ?

### ISSUE THREAD

**Issue by moisesnandres** [GeneralScripting/pipedrive-ruby#44]
Hi, I'm new on this, do I have to put 

```
require 'pipedrive-ruby'
Pipedrive.authenticate( YOUR_API_TOKEN )
Pipedrive::Deal.find( DEAL_ID )
```

in the gemfile ?
I have a form and I want to receive the information written there, in my pipedrive, so where do I put require: ... ?

**Comment by connorjacobsen** [comment]
`require 'pipedrive-ruby'` goes in your Gemfile.

If you are using rails, you will want to create an initializer, in a file like `config/initializers/pipedrive.rb` with the:

``` ruby
# config/initializers/pipedrive.rb
Pipedrive.authenticate( YOUR_API_TOKEN )
Pipedrive::Deal.find( DEAL_ID )
```
