### ISSUE TITLE
Pipedrive id is inaccessible due to OpenStruct id

### ISSUE THREAD

**Issue by lisadu** [GeneralScripting/pipedrive-ruby#5]
The id field returns the object id, not pipedrive id. For example, this will produce 
warning: Object#id will be deprecated; use Object#object_id

```
person = Pipedrive::Person.create
person.id
```

See http://stackoverflow.com/questions/4725329/override-id-on-a-ruby-object-created-using-openstruct

**Comment by mkrebber** [comment]
Please revert commit #fd8fd5f, cause it totally breaks the Pipedrive::Base class. 
Property id is not defined for OpenStruct class. Thx.

_/lib/pipedrive/base.rb:17:in `<class:Base>': undefined method`id' for class `Pipedrive::Base' (NameError)_

**Comment by jeanmartin** [comment]
done, sorry, I should've checked before following the advice...
